spring:
  application:
    name: Services
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: PandoraSQ123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080

  kafka:
    bootstrap-servers: localhost:9092